[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
