[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  # Lista de dependências externas que devem ser incluídas no pacote
  external_node_modules = ["puppeteer-core", "chrome-aws-lambda"]
  # Bundler para otimizar o código
  node_bundler = "esbuild"
  # Incluir arquivos necessários ao Chrome AWS Lambda
  included_files = ["node_modules/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
