[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
