[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["puppeteer-core", "chrome-aws-lambda"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
