[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/chrome-aws-lambda/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
